FROM openjdk:8

WORKDIR /usr/src/app

# curl
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y unzip;

# Pentaho
ENV PDI_RELEASE=8.1 \
    PDI_VERSION=8.1.0.0-365 \
    PDI_HOME=/opt/pentaho-di \
    KETTLE_HOME=/pentaho-di

RUN cd /tmp && \
	curl -LO https://downloads.sourceforge.net/project/pentaho/Pentaho%208.1/client-tools/pdi-ce-8.1.0.0-365.zip && \
	unzip -q /tmp/pdi-ce-8.1.0.0-365.zip -d ~/8.1 && \
	rm /tmp/pdi-ce-8.1.0.0-365.zip && \
	cd ~

ENV PATH=$PDI_HOME/data-integration:$PATH